# k8s/mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: octopent/flask-js-app-mysql-db:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Hesoyam@56
        - name: MYSQL_DATABASE
          value: flask_crud
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: initdb
        configMap:
          name: mysql-initdb-config
